[package]
name = "hello-world"
version = "0.2.3"
description = "Created with Kaptn"
edition = "2021"

[dependencies]
kaptn-lang = { path = "../../lang" }

[lib]
crate-type = ["cdylib", "lib"]
name = "hello_world"
