[package]
name = "ahoy-world"
version = "0.2.6"
description = "Created with Kaptn"
edition = "2021"
publish = false

[dependencies]
kaptn-lang = { path = "../../lang" }

[lib]
crate-type = ["cdylib", "lib"]
name = "ahoy_world"
