[package]
name = "hello-world"
version = "0.2.0"
description = "Created with Kaptn"
edition = "2021"

[dependencies]
kaptn-lang = { version = "0.2.0" }
solana-program = "2.0.8"

[lib]
crate-type = ["cdylib", "lib"]
name = "hello_world"
