[package]
name = "kaptn-syn"
version = "0.1.0"
description = "Macros for Kaptn Transfer Hook Framework"
license = "Apache-2.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1", features = ["full", "extra-traits", "parsing"] }
quote = "1"
proc-macro2 = "1"
