name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set env vars
      run: |
        source ci/rust-version.sh
        echo "RUST_STABLE=$rust_stable" >> $GITHUB_ENV
        source ci/solana-version.sh
        echo "SOLANA_VERSION=$solana_version" >> $GITHUB_ENV

    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ env.RUST_STABLE }}
    
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
